# Generated by Django 5.0.6 on 2024-05-15 22:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Airlines',
            fields=[
                ('airline_id', models.AutoField(primary_key=True, serialize=False)),
                ('image_url', models.URLField()),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Benefits',
            fields=[
                ('benefit_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('discount', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('service_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Cities',
            fields=[
                ('city_id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=3)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image_url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('surname', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('date_of_birth', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Countries',
            fields=[
                ('country_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('payment_id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(max_length=3)),
                ('date', models.DateField()),
                ('payment_operator', models.CharField(max_length=255)),
                ('cart_id', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Airplanes',
            fields=[
                ('airplane_id', models.AutoField(primary_key=True, serialize=False)),
                ('model', models.CharField(max_length=255)),
                ('onboard_number', models.CharField(max_length=255)),
                ('capacity', models.IntegerField()),
                ('airline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.airlines')),
            ],
        ),
        migrations.CreateModel(
            name='Airports',
            fields=[
                ('airport_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.cities')),
            ],
        ),
        migrations.AddField(
            model_name='cities',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.countries'),
        ),
        migrations.CreateModel(
            name='Flights',
            fields=[
                ('flight_id', models.AutoField(primary_key=True, serialize=False)),
                ('departure_time', models.DateTimeField()),
                ('arrival_time', models.DateTimeField()),
                ('airplane', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.airplanes')),
            ],
        ),
        migrations.CreateModel(
            name='Seats',
            fields=[
                ('seat_id', models.AutoField(primary_key=True, serialize=False)),
                ('seat_type', models.CharField(max_length=50)),
                ('seat_index_x', models.IntegerField()),
                ('seat_index_y', models.IntegerField()),
                ('airplane', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.airplanes')),
            ],
        ),
        migrations.CreateModel(
            name='Sightseeings',
            fields=[
                ('sightseeing_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image_url', models.URLField()),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.cities')),
            ],
        ),
        migrations.CreateModel(
            name='Voyages',
            fields=[
                ('voyage_id', models.AutoField(primary_key=True, serialize=False)),
                ('departure_airport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departure_airport', to='main.airports')),
                ('destination_airport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destination_airport', to='main.airports')),
            ],
        ),
        migrations.CreateModel(
            name='Tickets',
            fields=[
                ('ticket_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('date_of_birth', models.DateField()),
                ('passport_id', models.CharField(max_length=255)),
                ('gender', models.CharField(max_length=10)),
                ('citizenship', models.CharField(max_length=255)),
                ('airplane', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.airplanes')),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.flights')),
                ('voyage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.voyages')),
            ],
        ),
        migrations.AddField(
            model_name='flights',
            name='voyage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.voyages'),
        ),
        migrations.CreateModel(
            name='BoughtServices',
            fields=[
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='main.services')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.tickets')),
            ],
        ),
        migrations.CreateModel(
            name='TicketPayments',
            fields=[
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='main.payments')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.tickets')),
            ],
        ),
    ]
